CREATE TABLE USRROLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(100) DEFAULT NULL,
    role_name VARCHAR(100) DEFAULT NULL
);

CREATE TABLE USER (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    last_login TIMESTAMP NOT NULL,
    token VARCHAR(255),
    is_active BOOLEAN,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP
);

CREATE TABLE PHONE (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    number VARCHAR(10) NOT NULL,
    city_code VARCHAR(3) NOT NULL,
    country_code VARCHAR(3) NOT NULL,
    CONSTRAINT FK_PHONE_USER_ID FOREIGN KEY (user_id) REFERENCES USER (id)
);

CREATE TABLE USER_ROLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id UUID NOT NULL,
    usrrole_id BIGINT NOT NULL,
    CONSTRAINT FK_ROLE_USER_ID FOREIGN KEY (user_id) REFERENCES USER (id),
    CONSTRAINT FK_ROLE_USRROLE_ID FOREIGN KEY (usrrole_id) REFERENCES USRROLE (id)
);
